import { createServer } from 'http';
import { networkInterfaces } from 'os';
import { Server } from 'socket.io';
// @ts-ignore — handler.js is generated by `vite build` and doesn't exist at compile time
import { handler } from './build/handler.js';
import { setupSocketHandlers } from './src/lib/server/socket-handler.js';
import { seedDatabase } from './src/lib/server/seed.js';

const PORT = parseInt(process.env.PORT || '3000', 10);
const HOST = process.env.HOST || '0.0.0.0';

// Create HTTP server with SvelteKit handler
const httpServer = createServer(handler);

// Attach Socket.io
const io = new Server(httpServer, {
	cors: { origin: '*' },
	pingTimeout: 30000,
	pingInterval: 10000
});

// Wire up game logic
setupSocketHandlers(io);

// Seed database on first run
seedDatabase();

// Discover LAN IP for display
function getLanIp(): string {
	const nets = networkInterfaces();
	for (const name of Object.keys(nets)) {
		for (const iface of nets[name] || []) {
			if (iface.family === 'IPv4' && !iface.internal) {
				return iface.address;
			}
		}
	}
	return 'localhost';
}

// Start
httpServer.listen(PORT, HOST, () => {
	const lanIp = getLanIp();
	console.log(`\nScripture Showdown is running!\n`);
	console.log(`  TV:     http://${lanIp}:${PORT}/tv`);
	console.log(`  Phone:  http://${lanIp}:${PORT}/play`);
	console.log(`  Home:   http://${lanIp}:${PORT}/\n`);
});
